### ISSUE TITLE
Does AtomAI support GPU acceleration?

### ISSUE THREAD

**Issue by miaoleixin1994** [pycroscopy/atomai#6]
Dear Maxim,

Thanks for sharing this amazing package. I am trying out the r-VAE module after the workshop and I found it runs significantly slower than the VAE. First, I am wondering if this is usually the case and second, I am wondering if I can use GPU to accelerate the training. 

Thanks,
Leixin

**Comment by ziatdinovmax** [comment]
@miaoleixin1994 Thank you. Yes, it does support GPU. If a GPU device is available it will automatically transfer an initialized model and training data to GPU and use it to perform the training. This is true for all AtomAI's model (Segmentor, ImSpec, VAE, rVAE), as well as for custom PyTorch models that utilize AtomAI's trainers. 

The rVAE does indeed take a bit longer than conventional VAE to train due to differences in the decoder architecture. That said, it should not be THAT long. I just tested it on the rotated MNIST dataset of 60,000 images and with V100 GPU it takes ~7 minutes to converge after 100 training iterations. On a different GPU device, the execution time might be different. You can check if a model is transferred to GPU by running ```model.device``` after the model initialization and before ```model.fit()```. You can also check if GPU is seen/available by running  ```nvidia-smi``` (add an exclamation point at the beginning if running from a notebook). Hope this helps.

**Comment by miaoleixin1994** [comment]
Thank you very much for your answer!
